package com.campus.placement;
import com.campus.placement.model.*; import com.campus.placement.repository.*; import org.springframework.boot.CommandLineRunner; import org.springframework.context.annotation.Bean; import org.springframework.context.annotation.Configuration;
@Configuration public class DataSeeder{
 @Bean CommandLineRunner seed(StudentRepository sr,CompanyRepository cr,PlacementDriveRepository dr,ApplicationRepository ar,LearningResourceRepository lr,LiveOpportunityRepository lo){return args->{
  if(sr.count()==0){sr.save(student("AU021","Sanghavi Maganti","student@campus.local","AI",9.13,92,97,"python|java|sql|machine learning|pandas|git",4,1,90,88,72,90,80,84,"Not Placed"));sr.save(student("AU022","Ananya Rao","ananya@campus.local","CSE",8.72,91,95,"python|sql|java|git",3,1,82,86,84,88,80,84,"Not Placed"));sr.save(student("AU023","Rahul Kumar","rahul@campus.local","ECE",7.95,88,89,"c|python|sql|git",2,0,78,80,79,75,76,78,"Not Placed"));sr.save(student("AU024","Sneha Reddy","sneha@campus.local","AI",9.01,94,96,"python|pandas|sql|machine learning|power bi",4,1,91,90,88,92,89,91,"Placed"));sr.save(student("AU025","Vikram Singh","vikram@campus.local","CSE",8.20,86,90,"java|sql|git|spring boot",3,0,84,82,80,85,83,83,"Not Placed"));sr.save(student("AU026","Priya Sharma","priya@campus.local","AI",8.55,89,93,"python|javascript|html|css|react",3,1,80,84,90,87,85,85,"Not Placed"));sr.save(student("AU027","Meghana Das","meghana@campus.local","CSE",7.60,82,88,"java|sql|git",2,0,75,77,78,80,74,77,"Not Placed"));sr.save(student("AU028","Aditya Varma","aditya@campus.local","ECE",8.05,90,91,"python|docker|aws|sql|git",3,1,86,79,82,83,81,82,"Not Placed"));sr.save(student("AU029","Sanjana Patel","sanjana@campus.local","AI",8.88,93,94,"python|sql|pandas|power bi|git",4,2,88,92,87,90,88,89,"Not Placed"));sr.save(student("AU030","Anjali Gupta","anjali@campus.local","CSE",7.35,80,85,"javascript|html|css|nodejs",2,0,72,76,84,78,75,77,"Not Placed"));}
  sr.findByEmailIgnoreCase("student@campus.local").ifPresent(s->{if(s.getPassword()==null||s.getPassword().isBlank()){s.setPassword("demo123");sr.save(s);}});
  if(cr.count()==0){cr.save(company("TechNova","Software Developer",7.5,70,70,0,1,"CSE|AI|ECE","python|java|sql|git","Product engineering and cloud applications","Hyderabad","2026-06-01","2026-10-12","2026-10-15"));cr.save(company("DataSphere","Data Analyst",8.0,75,75,0,0,"CSE|AI|ECE","python|sql|pandas|power bi","Analytics and business intelligence","Hyderabad","2026-08-20","2026-10-20","2026-10-22"));cr.save(company("CloudWorks","Cloud Engineer",7.0,65,65,1,1,"CSE|AI|ECE","python|sql|aws|docker|git","Cloud infrastructure and DevOps","Bengaluru","2026-09-15","2026-11-03","2026-11-05"));cr.save(company("FinEdge","Software Engineer",8.5,80,80,0,0,"CSE|AI","java|sql|spring boot|git","Fintech engineering and secure services","Hyderabad","2026-05-10","2026-11-10","2026-11-12"));cr.save(company("InnoSoft","Full Stack Developer",7.25,70,70,0,0,"CSE|AI|ECE","javascript|html|css|react|nodejs","Modern web products and platforms","Pune","2026-09-25","2026-11-18","2026-11-20"));cr.save(company("Nexora AI","AI Engineer",8.8,80,80,0,0,"AI|CSE","python|machine learning|pandas|sql|git","New AI product company focused on applied ML","Hyderabad","2026-09-05","2026-10-28","2026-10-30"));}
  if(dr.count()==0){dr.save(drive("TechNova","Software Developer","2026-10-15","CSE|AI|ECE","Aptitude → Coding → Technical → HR"));dr.save(drive("DataSphere","Data Analyst","2026-10-22","CSE|AI|ECE","Aptitude → SQL → Case Study → HR"));dr.save(drive("CloudWorks","Cloud Engineer","2026-11-05","CSE|AI|ECE","Coding → Cloud Assessment → Technical → HR"));dr.save(drive("FinEdge","Software Engineer","2026-11-12","CSE|AI","Coding → Technical → Managerial → HR"));dr.save(drive("InnoSoft","Full Stack Developer","2026-11-20","CSE|AI|ECE","Coding → Project Review → Technical → HR"));dr.save(drive("Nexora AI","AI Engineer","2026-10-30","AI|CSE","ML Assessment → Coding → Technical → HR"));}
  if(ar.count()==0){ar.save(app("AU021","TechNova","Technical Interview","Shortlisted","2026-09-25"));ar.save(app("AU021","DataSphere","Aptitude Test","Applied","2026-09-28"));}
  seedLive(lo);
  if(lr.count()==0){lr.save(res("machine learning","Machine Learning Interview Sprint","Course","Intermediate","https://www.coursera.org/search?query=machine%20learning","Learn model evaluation, supervised learning and interview concepts.",12));lr.save(res("pandas","Pandas for Data Analysis","Practice","Intermediate","https://pandas.pydata.org/docs/getting_started/intro_tutorials/","Work through data cleaning, joins, grouping and analysis exercises.",6));lr.save(res("power bi","Power BI Dashboard Practice","Project","Intermediate","https://learn.microsoft.com/en-us/training/powerplatform/power-bi/","Build a small placement analytics dashboard.",8));lr.save(res("aws","AWS Cloud Foundations","Course","Beginner","https://aws.amazon.com/training/learn-about/cloud-practitioner/","Learn core cloud, compute, storage and IAM concepts.",10));lr.save(res("docker","Docker Essentials","Practice","Beginner","https://docs.docker.com/get-started/","Containerize a small application and understand images and containers.",6));lr.save(res("spring boot","Spring Boot REST API Practice","Project","Intermediate","https://spring.io/guides/gs/rest-service/","Build and test a REST API with validation and database access.",8));lr.save(res("react","React Frontend Practice","Project","Intermediate","https://react.dev/learn","Build a small dashboard with components, state and API calls.",8));lr.save(res("nodejs","Node.js Backend Practice","Project","Intermediate","https://nodejs.org/en/learn","Create a REST API and connect it to a database.",8));lr.save(res("java","Java Interview Practice","Practice","Intermediate","https://dev.java/learn/","Practice OOP, collections, exceptions and coding problems.",10));lr.save(res("sql","SQL Interview Practice","Practice","Intermediate","https://sqlbolt.com/","Practice joins, aggregation, subqueries and window functions.",7));lr.save(res("git","Git & GitHub Workflow","Practice","Beginner","https://skills.github.com/","Practice branching, pull requests and collaborative workflows.",4));lr.save(res("communication","Mock HR Interview Practice","Practice","All levels","https://www.toastmasters.org/resources/public-speaking-tips","Practice concise answers, introductions and behavioral interview responses.",5));lr.save(res("DSA","DSA Placement Problem Set","Practice","Intermediate","https://www.hackerrank.com/domains/data-structures","Solve arrays, strings, stacks, queues, trees and problem-solving sets.",15));}
 };}
 private Student student(String id,String name,String email,String branch,double cg,double t,double i,String skills,int p,int in,double c,double a,double comm,double res,double iv,double read,String status){Student s=new Student();s.setStudentId(id);s.setName(name);s.setEmail(email);s.setPassword(email.equals("student@campus.local")?"demo123":"demo123");s.setBranch(branch);s.setCgpa(cg);s.setTenthPercentage(t);s.setIntermediatePercentage(i);s.setSkills(skills);s.setProjects(p);s.setInternships(in);s.setBacklogs(0);s.setEducationGap(0);s.setCodingScore(c);s.setAptitudeScore(a);s.setCommunicationScore(comm);s.setResumeScore(res);s.setInterviewScore(iv);s.setReadinessScore(read);s.setPlacementStatus(status);return s;}
 private Company company(String n,String r,double cg,double t,double i,int b,int g,String br,String sk,String desc,String loc,String launch,String deadline,String drive){Company c=new Company();c.setName(n);c.setRole(r);c.setMinCgpa(cg);c.setMinTenth(t);c.setMinIntermediate(i);c.setMaxBacklogs(b);c.setMaxEducationGap(g);c.setBranches(br);c.setRequiredSkills(sk);c.setDescription(desc);c.setLocation(loc);c.setLaunchDate(launch);c.setApplicationDeadline(deadline);c.setDriveDate(drive);c.setSalary(salaryFor(n));return c;}
 private String salaryFor(String n){return switch(n){case "TechNova" -> "₹8 LPA"; case "DataSphere" -> "₹7.5 LPA"; case "CloudWorks" -> "₹9 LPA"; case "FinEdge" -> "₹8.5 LPA"; case "InnoSoft" -> "₹6.5 LPA"; default -> "₹6 LPA";};}
 private PlacementDrive drive(String c,String r,String d,String b,String p){PlacementDrive x=new PlacementDrive();x.setCompanyName(c);x.setRole(r);x.setDriveDate(d);x.setEligibleBranches(b);x.setProcess(p);return x;}
 private Application app(String s,String c,String st,String status,String date){Application a=new Application();a.setStudentId(s);a.setCompanyName(c);a.setStage(st);a.setStatus(status);a.setAppliedAt(date);return a;}
 private LearningResource res(String skill,String title,String type,String level,String url,String desc,int hours){LearningResource r=new LearningResource();r.setSkill(skill);r.setTitle(title);r.setType(type);r.setLevel(level);r.setUrl(url);r.setDescription(desc);r.setEstimatedHours(hours);return r;}
 private void seedLive(LiveOpportunityRepository r){
  String d="2026-10-03";
  live(r,"Jio","Graduate Engineering Trainee","Navi Mumbai",d,"2026-10-15","Freshershunt","https://freshershunt.in/off-campus-drive-jobs/off-campus-drive/","https://careers.jio.com/","engineering|communication","2026","B.E./B.Tech 2026; CGPA 6.0+; listed branches only","Jio Off Campus Drive 2026 — Graduate Engineering Trainee",true);
  live(r,"IBM","Associate System Engineer","Kolkata / Hyderabad",d,"Check official listing","Freshershunt","https://freshershunt.in/off-campus-drive-jobs/off-campus-drive/","https://www.ibm.com/careers/","python|java|automation|ai","2026 / 2027","0–1 year graduates; verify exact degree and location criteria","IBM Associate System Engineer 2026 — Cognitive Process Automation",true);
  live(r,"Virtusa","Graduate Technology / Testing Roles","Hyderabad",d,"Check official listing","Freshershunt","https://freshershunt.in/off-campus-drive-jobs/off-campus-drive/","https://www.virtusa.com/careers","java|testing|selenium|javascript|c#|gen ai","2026 / 2027","0–2 years; CS/IT degree for listed openings","Virtusa Off Campus Drive 2026 — 3 Hyderabad openings",true);
  live(r,"Tech Mahindra","International Voice Process / Fresher Roles","Hyderabad",d,"2026-10-10","Freshershunt","https://freshershunt.in/off-campus-drive-jobs/off-campus-drive/","https://careers.techmahindra.com/","communication|computer basics","2026","Check shift, education and batch requirements","Tech Mahindra Virtual Drive 2026",true);
  live(r,"NTT","MS Engineer L1","Bengaluru / Mumbai / Chennai",d,"Check official listing","Freshershunt","https://freshershunt.in/off-campus-drive-jobs/off-campus-drive/","https://careers.services.global.ntt/","networking|cloud|devops|communication","2026 / 2027","Entry-level; verify exact qualification","NTT Off Campus Drive 2026",true);
  live(r,"NTT DATA","Associate DevOps Engineer","Bengaluru",d,"Check official listing","Freshershunt","https://freshershunt.in/off-campus-drive-jobs/off-campus-drive/","https://careers.nttdata.com/","python|cloud|devops|linux","2026 / 2027","Entry-level; verify exact qualification","NTT DATA Associate DevOps Engineer 2026",true);
  live(r,"Accenture","S&C Global Network - AI - Data Science Associate","Bengaluru / Kolkata / Gurugram",d,"Check official listing","Freshershunt","https://freshershunt.in/off-campus-drive-jobs/off-campus-drive/","https://www.accenture.com/in-en/careers","python|sql|data science|machine learning|communication","2026 / 2027","0–2 years; check current role requirements","Accenture AI / Data Science Associate",true);
  live(r,"Avanade","Data Engineer Associate","Bengaluru",d,"Check official listing","Freshershunt","https://freshershunt.in/off-campus-drive-jobs/off-campus-drive/","https://www.avanade.com/en-in/career","python|sql|data engineering|cloud","2026 / 2027","Fresher listing; verify exact criteria","Avanade Data Engineer Associate",true);
  live(r,"DTCC","EDGE IT Analyst - Campus Program","Chennai / Hyderabad",d,"Check official listing","Freshershunt","https://freshershunt.in/off-campus-drive-jobs/off-campus-drive/","https://careers.dtcc.com/","java|sql|python|communication","2026 / 2027","Fresher campus program; verify exact batch","DTCC EDGE IT Analyst Campus Program",true);
  live(r,"Hewlett Packard Enterprise","External Intern - Technical","Bengaluru",d,"Check official listing","Freshershunt","https://freshershunt.in/off-campus-drive-jobs/off-campus-drive/","https://careers.hpe.com/","python|java|cloud|communication","2026 / 2027","Internship; verify current student requirements","HPE External Technical Internship",true);
 }
 private void live(LiveOpportunityRepository r,String c,String role,String loc,String posted,String deadline,String source,String sourceUrl,String apply,String skills,String batch,String eligibility,String desc,boolean verified){if(r.findByCompanyIgnoreCaseAndRoleIgnoreCaseAndPostedDate(c,role,posted).isPresent())return;LiveOpportunity o=new LiveOpportunity();o.setCompany(c);o.setRole(role);o.setLocation(loc);o.setPostedDate(posted);o.setDeadline(deadline);o.setSource(source);o.setSourceUrl(sourceUrl);o.setApplyUrl(apply);o.setRequiredSkills(skills);o.setBatch(batch);o.setEligibility(eligibility);o.setDescription(desc);o.setVerified(verified);r.save(o);}

}
